CREATE TABLE IF NOT EXISTS cliente (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(200) NOT NULL,
  email VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS pedido (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  id_cliente INT UNSIGNED,
  FOREIGN KEY (id_cliente) REFERENCES cliente(id)
)