DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS usuario;

CREATE TABLE IF NOT EXISTS usuario (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(120) NOT NULL,
  email VARCHAR(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS post (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  titulo VARCHAR(120) NOT NULL,
  conteudo TEXT NOT NULL,
  id_usuario INT UNSIGNED,
  FOREIGN KEY (id_usuario) REFERENCES usuario(id)
);