SELECT
  id,
  nome
FROM
  aula
WHERE
  -- USA-SE O % PARA QUE A PESQUISA VEJA SE A PALAVRA COMEÇA COM O ATRIBUTO PESQUSIADO

  nome like 'Módulo%';

SELECT
  id,
  nome
FROM
  aula
WHERE
  -- USA-SE O _ PARA QUE A PESQUISA SEJA EFETUADA
  -- E NO FINAL DA PALAVRA PESQUISADA AINDA EXISTA UMA LETRA
  nome like 'Módulo_';

SELECT
  id,
  nome
FROM
  aula
WHERE
 -- USA-SE O % NO INICIO PARA QUE A PESQUISA VEJA SE A PALAVRA TERMINA COM O ATRIBUTO PESQUSIADO
  nome like '%Módulo';


SELECT
  id,
  nome
FROM
  aula
WHERE
 -- USA-SE O %NOME%  PARA QUE A PESQUISA VEJA SE A PALAVRA EXISTE COM O ATRIBUTO PESQUSIADO
  nome like '%Módulo';